#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
usage: popgenvcf <command> [<args>...] [--help]

commands:
  stats     calculate stats from a VCF file

-h --help    show this

"""

from __future__ import division
import sys
from subprocess import call
from os.path import join, dirname
from docopt import docopt

if __name__ == '__main__':
    main_dir = join(dirname(__file__), '')
    args = docopt(__doc__,
                  version='version 0.1',
                  options_first=True)
    #print(args)

    argv = [args['<command>']] + args['<args>']
    if args['<command>'] == 'stats':
        exit(call(['python', main_dir + 'stats.py'] + argv))
    #elif args['<command>'] == 'view':
    #    exit(call(['python', main_dir + 'new_script.py'] + argv))
    else:
        exit("%r is not a popgenvcf command. See 'popgenvcf -h'." % args['<command>'])